version: '3.8'

name: searchbot

services:

  searchbot:
    container_name: searchbot
    hostname: searchbot
    build: ./
    depends_on:
      searchbot_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal
    command: sh -c "alembic upgrade head && python main.py"

  searchbot_db:
    container_name: searchbot_db
    image: postgres:15.1
    hostname: searchbot_db
    env_file:
      - .env
    volumes:
      - searchbot_data:/var/lib/postgresql/data/
    networks:
      - internal
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  searchbot_data:

networks:
  internal:
    driver: bridge