version: '3.8'

name: searchbot

services:

  tgbot-service:
    container_name: search-tgbot
    hostname: tgbot
    build: ./
    env_file:
      - .env
    networks:
      - internal

  postgres:
    container_name: search-postgres
    image: postgres:15.1
    hostname: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge